name: Build Rust CLI Binaries

on:
  push:
    branches: [ main, master ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

jobs:
  build:
    name: Build ${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          # Linux targets
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
            name: fn-linux-x86_64
            cross: false
          - target: aarch64-unknown-linux-gnu
            os: ubuntu-latest
            name: fn-linux-aarch64
            cross: true
          
          # macOS targets
          - target: x86_64-apple-darwin
            os: macos-latest
            name: fn-macos-x86_64
            cross: false
          - target: aarch64-apple-darwin
            os: macos-latest
            name: fn-macos-aarch64
            cross: false
          
          # Windows targets
          - target: x86_64-pc-windows-msvc
            os: windows-latest
            name: fn-windows-x86_64
            cross: false
          - target: aarch64-pc-windows-msvc
            os: windows-latest
            name: fn-windows-aarch64
            cross: true

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: ${{ matrix.target }}

    - name: Setup cache
      uses: Swatinem/rust-cache@v2
      with:
        key: ${{ matrix.target }}
        workspaces: rust-cli

    - name: Install cross-compilation tool
      if: matrix.cross
      shell: bash
      run: |
        cargo install cross --git https://github.com/cross-rs/cross

    - name: Build binary
      working-directory: rust-cli
      shell: bash
      run: |
        if [ "${{ matrix.cross }}" = "true" ]; then
          cross build --release --target ${{ matrix.target }}
        else
          cargo build --release --target ${{ matrix.target }}
        fi

    - name: Strip binary (Linux)
      if: matrix.os == 'ubuntu-latest' && matrix.cross == false
      working-directory: rust-cli
      shell: bash
      run: |
        strip target/${{ matrix.target }}/release/fn

    - name: Strip binary (macOS)
      if: matrix.os == 'macos-latest'
      working-directory: rust-cli
      run: |
        strip target/${{ matrix.target }}/release/fn

    - name: Create archive
      working-directory: rust-cli
      shell: bash
      run: |
        mkdir -p dist
        if [ "${{ matrix.os }}" = "windows-latest" ]; then
          cp target/${{ matrix.target }}/release/fn.exe dist/${{ matrix.name }}.exe
          cd dist && tar -czf ${{ matrix.name }}.tar.gz ${{ matrix.name }}.exe
        else
          cp target/${{ matrix.target }}/release/fn dist/${{ matrix.name }}
          cd dist && tar -czf ${{ matrix.name }}.tar.gz ${{ matrix.name }}
        fi

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.name }}
        path: rust-cli/dist/${{ matrix.name }}.tar.gz
        if-no-files-found: error

  release:
    name: Create Release
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    permissions:
      contents: write
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Download all artifacts
      uses: actions/download-artifact@v4
      with:
        path: artifacts

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: artifacts/*/*.tar.gz
        draft: true
        prerelease: false
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 